export const newTopPetsList = [
  {
    id: "1ca39446-4ea3-4091-bcd9-53aeecfb8414",
    type: "Cat",
    name: "Caesar",
    adoptionStatus: null,
    picture:
      "https://www.aspca.org/sites/default/files/cat-care_general-cat-care_body1-left.jpg",
    weight: 10,
    height: 30,
    color: "multicolor",
    bio: "Charlie is the most beautiful cat in the world",
    hypoallergenic: 0,
    dietaryRestrictions: "None",
    breed: "Beautiful",
    owner: null,
  },
  {
    id: "1fcff75f-6cb1-4f73-94e3-a63eb7bcb42f",
    type: "dog",
    name: "Mickey",
    adoptionStatus: "foster",
    picture:
      "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/white-lhasa-apso-dog-portrait-royalty-free-image-1643304064.jpg?crop=0.535xw:1.00xh;0.335xw,0&resize=480:*",
    weight: null,
    height: null,
    color: null,
    bio: null,
    hypoallergenic: 0,
    dietaryRestrictions: null,
    breed: null,
    owner: "08b177b3-666f-40ce-92a1-fc8ac7700734",
  },
  {
    id: "22f8ec1d-dd70-4cf0-bece-853678d22ff4",
    type: "dog",
    name: "Jackie",
    adoptionStatus: null,
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_9xrXA8hHwO5en_ouvrU7CH8ohbDGr9cGbaz54ytYAH9m1VnFDoJ7Qspe5rAlbjVfv7M&usqp=CAU",
    weight: null,
    height: null,
    color: null,
    bio: null,
    hypoallergenic: 1,
    dietaryRestrictions: null,
    breed: null,
    owner: null,
  },
  {
    id: "80ca4a8e-565b-49e6-8064-72cf91216b4c",
    type: "lizard",
    name: "Rex",
    adoptionStatus: null,
    picture:
      "https://www.orlandoexoticveterinarian.com/wp-content/uploads/2017/12/lizard-care-services.jpg",
    weight: 50,
    height: 80,
    color: null,
    bio: null,
    hypoallergenic: 0,
    dietaryRestrictions: null,
    breed: null,
    owner: null,
  },
];
